-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."CourseProjects" add column "updatedAt" timestamptz
--  null default now();
--
-- CREATE OR REPLACE FUNCTION "public"."set_current_timestamp_updatedAt"()
-- RETURNS TRIGGER AS $$
-- DECLARE
--   _new record;
-- BEGIN
--   _new := NEW;
--   _new."updatedAt" = NOW();
--   RETURN _new;
-- END;
-- $$ LANGUAGE plpgsql;
-- CREATE TRIGGER "set_public_CourseProjects_updatedAt"
-- BEFORE UPDATE ON "public"."CourseProjects"
-- FOR EACH ROW
-- EXECUTE PROCEDURE "public"."set_current_timestamp_updatedAt"();
-- COMMENT ON TRIGGER "set_public_CourseProjects_updatedAt" ON "public"."CourseProjects"
-- IS 'trigger to set value of column "updatedAt" to current timestamp on row update';
