-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Session" add column "questionaire_sent" Boolean
--  not null default 'false';
