# Generated by scripts/cloudflare_zone_inventory.sh — review before applying.
# Delete this file once the import has been applied; the blocks are then no-ops.

import {
  to = cloudflare_record.stujo_net["stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/ce6320a5764385535420e9e3ef8193db"
}

import {
  to = cloudflare_record.stujo_net["en.stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/c9cb96b4ec0e4dffeb6cfb64d4370de9"
}

import {
  to = cloudflare_record.stujo_net["cau.stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/d0a2dacca232725add325d360951fe47"
}

import {
  to = cloudflare_record.stujo_net["haw-kiel.stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/f02496981fc63f876c4676d4e9b7ee6d"
}

import {
  to = cloudflare_record.stujo_net["fh-kiel.stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/0c52a82a2ff281328d283599e6dc9d24"
}

import {
  to = cloudflare_record.stujo_net["flensburg.stujo.net"]
  id = "9ea84345f080122580324aae618ea5f7/1ab35f4a5cafabdf89b8ce949b52d145"
}

import {
  to = cloudflare_record.stujo_net_www[0]
  id = "9ea84345f080122580324aae618ea5f7/ad95afc917cac5d78dd681060a0a75a2"
}
