-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "public"."CourseEnrollment" ADD CONSTRAINT "uniqueUserCourse" UNIQUE("userId", "courseId");
