FROM quay.io/keycloak/keycloak:26.7.2 as builder

ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=dev-file
COPY ./libs/keycloak-bcrypt-1.6.0.jar /opt/keycloak/providers/
COPY ./libs/matrix-handle-listener.jar /opt/keycloak/providers/
COPY ./themes/opencampus /opt/keycloak/themes/opencampus
COPY ./themes/edu-hub /opt/keycloak/themes/edu-hub
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.7.2
# Copy the full pre-built (augmented) server so `start --optimized` can skip the
# Quarkus augmentation at runtime instead of rebuilding on every container boot.
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENV KC_HOSTNAME_STRICT=false
ENV KC_HTTP_ENABLED=true
ENV KC_HTTP_HOST=0.0.0.0

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized", "--import-realm"]
