#key cloak 17 does not work for my development at all, had to roll back to v16, including changes in docker-compose.yml
FROM jboss/keycloak:16.1.1
COPY ./libs/keycloak-bcrypt-1.5.0.jar /opt/jboss/keycloak/standalone/deployments/