DELETE FROM "public"."MailTemplate" WHERE "type" IN
  ('JOB_POSTING_PUBLISHED', 'JOB_POSTING_EXPIRED', 'JOB_POSTING_ADMIN_NOTICE', 'JOB_POSTING_PAYMENT_FAILED');
DELETE FROM "public"."MailTemplateType" WHERE "value" IN
  ('JOB_POSTING_PUBLISHED', 'JOB_POSTING_EXPIRED', 'JOB_POSTING_ADMIN_NOTICE', 'JOB_POSTING_PAYMENT_FAILED');
