-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Program" add column "achievementCertificateTemplateTextId" integer
--  null;
