DELETE FROM "public"."MailTemplate"
WHERE "courseId" IS NULL AND "type" IN (
  'PROJECT_JOIN_REQUESTED',
  'PROJECT_JOIN_ACCEPTED',
  'PROJECT_JOIN_DECLINED',
  'PROJECT_AUTHOR_EXCLUDED',
  'PROJECT_TEAM_CONFIRMED',
  'PROJECT_SENT_BACK',
  'PROJECT_SUBMITTED',
  'PROJECT_APPROVED',
  'PROJECT_REJECTED',
  'PROJECT_DEADLINE_REMINDER'
);

DELETE FROM "public"."MailTemplateType" mtt
WHERE mtt."value" IN (
  'PROJECT_JOIN_REQUESTED',
  'PROJECT_JOIN_ACCEPTED',
  'PROJECT_JOIN_DECLINED',
  'PROJECT_AUTHOR_EXCLUDED',
  'PROJECT_TEAM_CONFIRMED',
  'PROJECT_SENT_BACK',
  'PROJECT_SUBMITTED',
  'PROJECT_APPROVED',
  'PROJECT_REJECTED',
  'PROJECT_DEADLINE_REMINDER'
)
AND NOT EXISTS (SELECT 1 FROM "public"."MailTemplate" mt WHERE mt."type" = mtt."value");
