DELETE FROM "public"."MailTemplate"
  WHERE "type" IN ('GUEST_REGISTRATION_CONFIRM', 'GUEST_ALREADY_HAS_ACCOUNT') AND "courseId" IS NULL;

DELETE FROM "public"."MailTemplateType"
  WHERE "value" IN ('GUEST_REGISTRATION_CONFIRM', 'GUEST_ALREADY_HAS_ACCOUNT');
