-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."ProjectEnrollment" add column "rating" text
--  not null default 'UNRATED';
