-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."RentAScientistConfig" add column "test_operation" boolean
--  not null default 'true';
