# https://blog.nrwl.io/create-a-next-js-web-app-with-nx-bcf2ab54613
FROM node:16-alpine

RUN apk add --no-cache libc6-compat yarn socat

WORKDIR /opt/app

RUN yarn --frozen-lockfile

CMD [ "sh", "dev-edu.sh" ]
