# Fixed version to node 16, as node 17 is not supported by some dependencies
# 1. Install dependencies only when needed
FROM node:18-alpine AS deps

RUN apk add --no-cache libc6-compat

RUN corepack enable

WORKDIR /opt/app

COPY package.json /opt/app
COPY yarn.lock /opt/app
COPY .yarn/ /opt/app/.yarn
COPY .yarnrc.yml /opt/app

RUN yarn --immutable

# 2. Rebuild the source code only when needed
FROM node:18-alpine AS builder

WORKDIR /opt/app

COPY --from=deps /opt/app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_AUTH_URL
ENV NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

ARG NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}

ARG NEXT_PUBLIC_HELP_DOCS_URL
ENV NEXT_PUBLIC_HELP_DOCS_URL=${NEXT_PUBLIC_HELP_DOCS_URL}

ARG NEXT_PUBLIC_STORAGE_BUCKET_URL
ENV NEXT_PUBLIC_STORAGE_BUCKET_URL=${NEXT_PUBLIC_STORAGE_BUCKET_URL}


RUN npx nx run edu-hub:build

# 3. Production image, copy all the files and run next
FROM node:18-alpine AS runner

WORKDIR /opt/app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /opt/app/dist/apps/edu-hub/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /opt/app/dist/apps/edu-hub/.next/static ./dist/apps/edu-hub/.next/static
COPY --from=builder --chown=nextjs:nodejs /opt/app/dist/apps/edu-hub/public ./apps/edu-hub/public
# Temporary fix to fix image generation
# https://github.com/vercel/next.js/issues/48077
# COPY --from=builder /opt/app/dist/apps/edu-hub/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /opt/app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker

WORKDIR /opt/app/apps/edu-hub

USER nextjs

EXPOSE 25000

ENV PORT 25000

# CMD [ "node", "server.js" ]
CMD [ "node", "server.js" ]
