table:
  name: AppSettings
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - appName
        - backgroundImageURL
        - bannerBackgroundColor
        - bannerFontColor
        - bannerTextDe
        - bannerTextEn
        - created_at
        - defaultLocale
        - domain
        - faqCollectionName
        - faviconUrl
        - guestDataRetentionMonths
        - imprintUrl
        - logoUrl
        - previewImageURL
        - primaryColor
        - privacyUrl
        - secondaryColor
        - showFaqSection
        - termsUrl
        - timeZone
        - updated_at
      filter: {}
