DELETE FROM "public"."MailTemplate"
  WHERE "type" IN ('JOB_ORGANIZATION_CLAIMED', 'JOB_ORGANIZATION_ACCESS_REQUEST') AND "courseId" IS NULL;

DELETE FROM "public"."MailTemplateType"
  WHERE "value" IN ('JOB_ORGANIZATION_CLAIMED', 'JOB_ORGANIZATION_ACCESS_REQUEST');
